-- BaseModel CRUD + Query tests
CREATE TABLE IF NOT EXISTS t_user (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    email VARCHAR(200)
);

-- UUID32 ID strategy
CREATE TABLE IF NOT EXISTS t_uuid32 (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(100),
    age INT
);

-- UUID36 ID strategy
CREATE TABLE IF NOT EXISTS t_uuid36 (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(100),
    age INT
);

-- AUTO_INCREMENT ID strategy
CREATE TABLE IF NOT EXISTS t_auto_inc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age INT
);

-- Data fill tests (SimpleModel with auto-fill fields)
CREATE TABLE IF NOT EXISTS t_data_fill (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    create_user BIGINT,
    created_time TIMESTAMP,
    updated_time TIMESTAMP
);

-- ModelOperator tests
CREATE TABLE IF NOT EXISTS t_operator (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    email VARCHAR(200)
);

-- FieldCustomizer cascade tests
CREATE TABLE IF NOT EXISTS t_cascade_child1 (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    created_time TIMESTAMP
);
CREATE TABLE IF NOT EXISTS t_cascade_child2 (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    created_time TIMESTAMP
);

-- DynamicModel tests
CREATE TABLE IF NOT EXISTS t_dynamic (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    age INT
);
