name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [17, 21]
        distribution: ['temurin']
      fail-fast: false
      max-parallel: 5
    name: Test JDK ${{ matrix.java }}-${{ matrix.distribution }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: ./mvnw test -B -D"license.skip=true"
